### ISSUE TITLE
addon catalog (CatalogFiltered): no installed addons

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#102]
Using `CatalogFiltered` and `addonCatalogs` for addons is great, but it has a flaw: there are no installed addons in the catalog

this can be solved:

- at a UI level, add another route `/installed` which just displays `ctx.content.addons` with some filtering
- by wrapping `CatalogFiltered` and adding installed by splitting the Load action into `Installed(type)` or `Catalog(resource_ref)`; this has two extra advantages:
   * allows to structure the navigation conveniently at a model level (we can choose between `catalog -> type` or `type -> catalog`) 
   * different Load action for addons; otherwise we have to wire msgs in the app in such a way that only `model.discover` or only `model.addons` will receive a certain Load
   * we can also implement addon search, see #93 
- ~~by creating a fake addon~~

**Comment by nklhrstv** [comment]
its done on the UI level before core
