### ISSUE TITLE
proper crate name 

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#125]
currently, the derive macro fails when it's used in `stremio-core` itself

to solve this, we should check if the name of the currently compiled crate is `stremio-core`, and if so, use `"crate"`; else, use `crate_name("stremio-core").unwrap_or_else(||...panic...)`,

**Comment by MartinKavik** [comment]
I see you already fixed it
https://github.com/Stremio/stremio-core/blob/d41688c2f54b6ffe764073b8e38acc71271fc3e8/stremio-derive/src/lib.rs#L15
So I think we can close it.

---

Other solutions FYI:
  - Add `self` alias in `stremio-core`'s `lib.rs` - https://github.com/rust-lang/rust/issues/56409#issue-386461785
  - Find out if we are in `stremio-core` - https://github.com/rust-lang/rust/issues/54647#issuecomment-429166393

---

OT: Do we have plans to integrate a CI/CD pipeline with tests to prevent similar issues?

**Comment by Ivshti** [comment]
it's not fixed as far as I understand it, since `crate_name` may fail if `stremio-core` is not added as a dependency

We must be able to distinguish between not being added as a dep, and being the crate itself

re CI: good idea. just a simple travis file for a rust project should do the trick, feel free to try
