### ISSUE TITLE
Youtube streaming issue

### ISSUE THREAD

**Issue by citkane** [Stremio/stremio-core#143]
I hope this is an acceptable place for this issue. I cannot find a dedicated repo for the node `server.js` main file in the Stremio app.

My problem has been for the last few months that Youtube videos, including trailers, just wont establish a link. I tracked the problem down to the `parseFormats` function in the main node `server.js` file, version 4.5.0, line no. 137139.

The replacement code below has my Stremio working as expected again. Looks like Youtube may have changed their API behavior as `info.url_encoded_fmt_stream_map` and `info.adaptive_fmts` are `undefined`, but usable data exists under `info.player_response.streamingData.formats`.
```
exports.parseFormats = (info) => {
  let formats = [];
  if (info.url_encoded_fmt_stream_map) {
    formats = formats
      .concat(info.url_encoded_fmt_stream_map.split(','));
  }
  if (info.adaptive_fmts) {
    formats = formats.concat(info.adaptive_fmts.split(','));
  }

  formats = formats.map((format) => qs.parse(format));
  if(info.player_response.streamingData && info.player_response.streamingData.formats) {
	  formats = formats.concat(info.player_response.streamingData.formats);
  }
  delete info.url_encoded_fmt_stream_map;
  delete info.adaptive_fmts;

  return formats;
};
```
Edit: After some testing, older videos have the original formats location while newer videos have the formats under `info.player_response.streamingData.formats`. The code above is now working for all Youtube videos.

**Comment by Ivshti** [comment]
Are you sure you're testing with the latest `server.js`? we recently updated ytdl-core to fix one of these issues

**Comment by citkane** [comment]
The file header says "version 4.5.0".

I am running Stremio on Ubuntu 18.04, installed from the .deb from their website.
Youtube videos stopped working for me a few months ago - that is why I started digging in the code.

Maybe the issue is unique to the .deb bundle?

**Comment by Ivshti** [comment]
That makes sense

The issue is indeed unique to the .deb since it's the only thing we didn't update

Sorry for causing you to have to debug this on your own - the patch was actually done in ytdl-core a while back, here's an up to date version of server.js you can use: https://dl.strem.io/four/master/server.js

**Comment by ewwink** [comment]
where are source code of server.js for android? I tried above but the app force close.

**Comment by Ivshti** [comment]
@nklhrstv can help with this

**Comment by nklhrstv** [comment]
@ewwink 
The link above is for a bundle of the streaming server used in the desktop app.
[This](http://stremio-artifacts.s3.amazonaws.com/server/android/v4.12.0/server.js
) is the latest streaming server bundle that targets android. 
The latest andorid release uses older version of the streaming server and was never tested with the latest one. 
Text me if you have any issues.

**Comment by ewwink** [comment]
@nklhrstv thank you very much
