### ISSUE TITLE
Stremio Flatpak version

### ISSUE THREAD

**Issue by FinixFighter** [Stremio/stremio-core#147]
Hi! I wanted to ask you if you can create a flatpak version of Stremio, it would be easier for people using Linux to find  the app, because they'll have it in their repo. This is the submission wiki: https://github.com/flathub/flathub/wiki/App-Submission :)

**Comment by Ivshti** [comment]
this repo is for the internal library that stremio uses

the repo that packages the app is stremio-shell, and there's already a flatpak version here: https://github.com/Stremio/stremio-shell/issues/109

Hope that helps
