### ISSUE TITLE
Addon Settings: Do not install addons that need configuration

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-core#150]
Addon settings will be handled by setting `behaviorHints` in the manifest:
```
manifest {
    behaviorHints: {
        configurable: true,
        configurationRequired: true
    }
}
```

If `behaviorHints.configurable` and `behaviorHints.configurationRequired` are both `true`, then the addon requires configuration in order to work at all, so installation of the addon should not be possible in this case.

This situation should be handled in `stremio-core`, and installation of the addon should be rejected if these 2 `behaviorHints` are `true`.

**Comment by YanivBir** [comment]
Hi @nklhrstv and @jaruba,
I can handle it, could you provide some direction to: which files/area of the code is relevant for it?
Thanks.

**Comment by nklhrstv** [comment]
https://www.github.com/Stremio/stremio-core/tree/development/src%2Ftypes%2Faddon%2Fdescriptor.rs
you need to add flags here 
and then modify InstallAddon action handler in models/ctx/ dir.

**Comment by nklhrstv** [comment]
@jaruba how to confirm if a manifest is configured ?

**Comment by jaruba** [comment]
@nklhrstv There is no current way of knowing if an addon is already configured or not. But the concept is that configured addons are not handled any differently by the apps at all, so why do we need to know if the addon is already configured or not in `stremio-core`?

**Comment by nklhrstv** [comment]
i forgot how to determine in an addon should be installed or not

**Comment by nklhrstv** [comment]
@YanivBir so InstallAddon action handler should return error event if there is 'configurationRequired' in the descriptor's flags
