### ISSUE TITLE
Detail model: upcoming vs released videos

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#17]
the detail model should split `videos` in `upcoming` and `released`, and should use the `released` property (date) of the `Video` object to decide

this is related https://github.com/Stremio/stremio-cinemeta/issues/36

**Comment by nklhrstv** [comment]
we did that on ui level by putting upcomming label in every video. i think there is no need to touch core for this

**Comment by Ivshti** [comment]
agreed
