### ISSUE TITLE
migrate to async/await

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#2]
it's doable in rust 2018, but it requires wasm-bindgen to migrate to futures 0.3

see https://github.com/rustwasm/wasm-bindgen/issues/1126

and https://www.reddit.com/r/rust/comments/bphw68/wasmbindgen_v0244_has_support_for_futures_03_and/

it could be very ergonomic, e.g.

```
    let (platform, uptime) = try_join!(platform_future, uptime_future)?;
```

Also see this: https://docs.rs/dtolnay/0.0.3/dtolnay/macro._01__await_a_minute.html

**Comment by Ivshti** [comment]
or perhaps sooner: https://docs.rs/dtolnay/0.0.3/dtolnay/macro._01__await_a_minute.html

esp with the compat layer, we can migrate gradually; first, move from combinators to `async fn`, then migrate the `Environment` and `Effect` traits

**Comment by nklhtv** [comment]
migration to async/await and futures 0.3 has been done
