### ISSUE TITLE
HLS streams support

### ISSUE THREAD

**Issue by nklhrstv** [Stremio/stremio-core#225]
What is the best way to add support for HLS streams?
1. add a flag in Stream's behavior hints that must be set to true if the `stream.source` has url that leads to m3u8 playlist.
2. add HLS variant to StreamSource enumeration. Could be something like:
```Rust
HLS { m3u8: Url }
```
3. parse the url in stremio-video and check if it ends with `.m3u8`

or maybe something else?

**Comment by Ivshti** [comment]
It's definitely 3

A URL to a m3u8 should be treated the same as a URL to a mp4 - all video players do that. So it should be a regular `url` stream source. 

and then the video player should recognize when the URL points to .m3u8 - this can happen in two ways
1. worse way: based on extension
2. better way: based on returned header - see this https://github.com/Stremio/stremio-players/blob/master/html5-with-ssmiddlewares.md  - it already makes a HEAD request before deciding what to do with a stream
