### ISSUE TITLE
Next episode button

### ISSUE THREAD

**Issue by mpetuska** [Stremio/stremio-core#242]
Currently streamio already supports loading into the next episode once current play reaches the end. It'd be great to have an explicit button for this to allow skipping end credits

**Comment by 4ndual** [comment]
Pls

**Comment by TRtomasz** [comment]
Closing in favour of https://github.com/Stremio/stremio-features/issues/157 
also, this is the wrong repository guys, please use stremio-features or stremio-bugs.
