### ISSUE TITLE
suggestion to avoid duplication

### ISSUE THREAD

**Issue by jadsongmatos** [Stremio/stremio-core#247]
something that can be observed mainly in the torrent, for example, in a film with several versions of the same film in different languages, thinking about a way to improve this situation. I thought of a video player where the image would load separately from the audio, that way the audio could be loaded and synchronized in the same way as a subtitle system.

improving image transmission performance and avoiding duplication

**Comment by nklhtv** [comment]
those are not really duplications since they could be from different source, in different resolution or with different codec.
audio & video streams from different files will be out of sync and syncing them manually wont be a good UX
