### ISSUE TITLE
Stremio not quitting

### ISSUE THREAD

**Issue by gmelodie** [Stremio/stremio-core#248]
The `quit` option simply doesn't work. Here's a workaround bash function I added to my `.bashrc` to quit stremio:

```bash
# workaround for stremio not closing bug
function close_stremio {
    for process in $(ps aux | grep stremio | cut -d " " -f 5); do
        kill -9 $process 2>/dev/null;
    done
}
```

And call it from the terminal:
```bash
$ close_stremio
```

Obs: I'm using Ubuntu 20.04 and Stremio 4.4.137

**Comment by TRtomasz** [comment]
Hi, thanks for your report. Please notice this is not correct repository for this issue. Please use stremio-bugs or stremio-shell in the future as this is shell related. 
Sadly i couldnt reproduce it(check video). Please try to start stremio from terminal and check if there are any error messages when you use quit button from settings.

https://user-images.githubusercontent.com/40594253/119662435-4d045c00-be29-11eb-885a-060320415fa9.mp4

**Comment by gmelodie** [comment]
Thank you! Posted more information I was able to find over to the correct repo. https://github.com/Stremio/stremio-bugs/issues/295
