### ISSUE TITLE
Subtitles delay feature doesn't works in the android app

### ISSUE THREAD

**Issue by pedrorojasg** [Stremio/stremio-core#255]
Hi Stremio team! Shout out for your work!

So, currently in the last version of the android app, the subtitles delay doesn't have any effect.

**Comment by jaruba** [comment]
@pedrorojasg Hi, I can reproduce your issue, we'll look into it. Thank you for reporting it!

**Comment by pedrorojasg** [comment]
Now it is solved in the last android version 1.4.4.

Thanks a lot @jaruba
