### ISSUE TITLE
self hosting

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Stremio/stremio-core#268]
Can i self host the emails aspect of stremio? so instead i connect to your servers and collect uneeded data (yes, collecting stuff as type and language, device identifier numbers is undeeded) i conect to my server and keep my data secure

**Comment by TRtomasz** [comment]
No, this is not possible, sorry.

**Comment by Ivshti** [comment]
@EsmailELBoBDev2 I'd like to add that we don't collect any of the data you mentioned. If you've found proof of the opposite please email security@stremio.com

**Comment by EsmailELBoBDev2** [comment]
@TRtomasz Oh okay, thanks! can you guys make it possible then? it would be nice i mean it's already FOSS so i don't see why i can't just self host it's server

@Ivshti Weird, i got this info from privacy policy 

> Log information:
When you use our Services, some data is automatically collected. Such data could include your computer's Internet Protocol (“IP”) address, operating system,***type and language, device identifier numbers***, and the time and date of your use. The log information is collected to provide a stable, secure and pleasant experience for users on the Services and to ensure the performance, correctness, security and reliability of our Services. 

https://www.stremio.com/privacy
