### ISSUE TITLE
Are stremio analytics client side or server side?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Stremio/stremio-core#269]
i'm curious to know if collected data mentioned in your privacy policy collected client side or maybe you use some fancy PHP code on your server and you collect data server side only? and if it's client side where it's file in stremio core?

**Comment by rleroi** [comment]
It seems this file https://github.com/Stremio/stremio-core/blob/development/stremio-analytics/src/lib.rs sends certain events back to the Stremio API server.

**Comment by Bananaman** [comment]
I am guessing that Cinemeta's "Popular TV/Movies" lists are all based on analytics from Stremio users, which is really cool if that's the case since it's a good sign of what people actually like watching.

**Comment by nklhtv** [comment]
Analytics events are collected only from authenticated users.

**Comment by Bananaman** [comment]
Okay so it's collected from everyone unless "Guest" is clicked on the Stremio login screen instead. :)

Anyway, I don't mind contributing analytics.

**Comment by EsmailELBoBDev2** [comment]
@Bananaman Are you sure? https://github.com/Stremio/stremio-core/issues/268#issuecomment-982134526 it seems they collect more than what they need. at least for me...
