### ISSUE TITLE
UX: Show ratio between download speed and playback speed in the streaming report hover, or show buffering in the scrubber?

### ISSUE THREAD

**Issue by aminomancer** [Stremio/stremio-core#271]
The streaming report shows buffered percent, under network status. So it might say 7%, but then to ascertain whether I'm gonna have uninterrupted playback, I have to look at the playhead and estimate if I'm ahead or behind 7%. I read that people are very bad at visually estimating distances. Usually people cannot even identify the halfway mark on a scrubber. We have a bias to one side or the other so consistently estimate the halfway mark at like 40% or 60%. I know it's especially hard the bigger the scrubber is, and for a video player app it's gonna be huge. So it's very hard to tell how close I am to reaching the end of the buffered data.

At the same time, even knowing the distance between buffered data and current playback position would not be as helpful as knowing the current ratio between download speed and playback speed. Since even if playback is currently buffering, if that ratio is positive, I know it'll eventually right itself and won't happen again. Whereas if playback is currently fine but that ratio dips into the negative and stays that way, I know it'll eventually run into problems. Which is often the case with large torrents with few seeders. So knowing the ratio can make the difference between staying on a given torrent versus trying to find another one, or just giving up on the title altogether.

Thanks 🙏

**Comment by TRtomasz** [comment]
I really dont think this rules about distance applies to percentage. Also ratio between "download speed and playback speed" sounds way more complicated then. That kind of feature would make UI more complicated and harder to understand.

**Comment by aminomancer** [comment]
No idea what you mean. Percentages and ratios are exactly what I'm talking about. If you can't even tell where "half" is, it's even harder to tell where "7%" is on a super long scrubber.

Ratio between download speed and playback speed is incredibly simple. It's a real positive number. If you cap it at two decimal places it takes up very little space in the streaming report hover. I don't see how it's any different from the information already displayed under network status, except that it's more practical. It wouldn't make the UI more complicated or harder to understand at all, since it would only appear in the streaming report hover. Maybe you misunderstand what I'm talking about. If you hover the globe icon in the control bar, a popup appears with torrent information. This is where a ratio would fit.

Clearly I understand that download speed is time-dependent, since I clearly said "current ratio between download speed and playback speed" and "if playback is currently fine but that ratio dips into the negative and stays that way, I know it'll eventually run into problems." Download speed changing is exactly why this feature is necessary. There's no guarantee that playback isn't going to stop at some point, but clearly the chances are worse if the average ratio between download speed and playback speed over the course of playback has been less than 1.0. For a program that plays back torrent files in real-time I'd think that would be considered an essential, basic feature.
