### ISSUE TITLE
initShellComm is not defined.

### ISSUE THREAD

**Issue by gopalsays108** [Stremio/stremio-core#274]
User Interface could not be loaded.
Does anyone know how to fix it?

![image](https://user-images.githubusercontent.com/68118204/149616871-bcafcd50-1922-47e3-a189-d0991a7528a0.png)

**Comment by rishabhgusain6** [comment]
Well, the same issue happened with me today
Here is what I did (not a laid out method, just trial n error but it worked)
1. I uninstalled Stremio (cleared all user data too as I have account) and reinstalled it (This step may not be necessary)
2. I connected to a VPN, Proton VPN in my case and opened stremio (ensure stremio is fully closed even from sys tray before connecting to VPN)
3. Booom, it opened. I roamed in the app for 2-3 mins and then disconnected VPN
4. After that its working as normal

**Note:** 
_‣If above method doesn't work u may even need to check GPU driver update
‣I am using Windows 11 (it may affect but most probably it won't be much of an affecting factor)_

**Possible explanations for the issue:** (will edit this)
- Some internet rerouting or maybe even ISP/Firewall Blocking site access
