### ISSUE TITLE
Installed addon manifest properties lost

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-core#284]
When installing a new addon, properties that are not part of the rust schema are lost when pushed to API, this can lead to errors when using these addons in other apps (especially when addon manifest defines legacy properties that are shimed correctly in other apps).

**Comment by nklhtv** [comment]
the only possible way is to add flatten hashmap to every struct thats used in Manifest.
The correct solution to this issue will be to shim the legacy props. Eventually all apps and addon-sdk should use stremio-core for validation.
