### ISSUE TITLE
Deserialize null or undefined strings to null object

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-core#285]
Sometimes strings from addons `year/runtime` might be `null/undefined` due to the way they're handled in addon. It might be a good idea to check for these when deserializing and return actual `null` instead of a string

**Comment by nklhtv** [comment]
could be implemented with custom deserializer that returns
Option::deserialize(deserializer)?.filter(|value| /../)

**Comment by core1024** [comment]
I think if this is an issue it is issue with the addon. I am pretty sure Stremio 4 will also show the string `null/undefined` if that's provided from the addon. The `release_info` (`year`) and `runtime` fields are plain text fields. For example for series we show the `release_info` as range of years like `2019-2021` or even `2022-` some addon author may choose to show the year as `'98`, other may have a bug and display `[object Object]`. It's pointless to blacklist some random words for these fields.

**Comment by nklhtv** [comment]
i agree those are addon issues we try to solve on the client.
