### ISSUE TITLE
Handle streams for Youtube channel meta videos

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-core#312]
Currently apps based on `core` cannot play Youtube meta videos without special handling, because youtube addon does not provide any streams. In currently used Stremio apps there's special handling for Youtube video streams retrieval in `stremio-aggregators`:
https://github.com/Stremio/stremio-aggregators/blob/9d1665b20b5a9ae737164b191a401817a53cabe0/lib/streams.js#L51-L56
To not break any existing addons depending on this logic `core` should support something similar:
 - Either populate `video.streams` array with a single `stream` object for each video when returning Youtube meta (and possibly avoid doing another request to get streams)
 - Or when doing `streams` retrieval for a `videoId` append single stream with that id to the results

Probably the 2nd options is better, since the first one would increase the `metaItem` size quite a bit on channels with large amount of videos.

**Comment by nklhtv** [comment]
special cases for youtube metaitem/video/stream deeplinks are implemented now
requesting streams for a yt_id meta will generate single stream for that video if none are specified in video.streams
