### ISSUE TITLE
LibraryByType improvements

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-core#322]
When leaving the page usually you need to unload cosumed fields, but doing this for `LibraryByType` and then again trying to load `LibraryByType` will return empty catalogs. If state is not cleared and you have scrolled to the next page for some type, and then go to library again it will load that page for initial state, but it should again start from 1st page.

Also it seems `LibraryByType` doesn't respect the sort passed in the request
Also it seems that after logging in for the first time, if your lib has a bigger size, then current `library_by_type` won't be loaded and only will work on restart. Seems there some sort of race condition. Simple `library` state works fine.

**Comment by nklhtv** [comment]
Done
