### ISSUE TITLE
[ Feature Request ] Option to Preferably Choose Embedded Subtitle by Language

### ISSUE THREAD

**Issue by 8227846265** [Stremio/stremio-core#324]
Hello, I would like to suggest giving an option for user to choose embedded subtitles over online subtitles.

For example, in the settings
- Default Language: English
- Default Subtitle: English
- Subtitle Preference:
A. Embedded Subtitle First
B. Online Subtitle First

There are torrents that have included subtitles that have better timing than its online counterpart.

Subtitle logic:
- If embedded subtitle is not available, choose online subtitle, if both are not available, choose none
- If online subtitle is not available, choose embedded subtitle, if both are not available, choose none

**Comment by TRtomasz** [comment]
@8227846265 this is wrong repository for creating such issues.
But this is already implemented in both stremio desktop and stremio mobile apps. Embedded subs are preffered over online subtitles.
