### ISSUE TITLE
Catalog Titles in Board Should be Like the Ones in Stremio v4

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-core#325]
This is how it looks in Stremio Web:
<img width="348" alt="Screenshot 2022-06-13 at 16 14 36" src="https://user-images.githubusercontent.com/1777923/173362545-803cf780-4307-40d2-a5db-8cad8859cb14.png">

This is how it should look (same catalog in Stremio v4):
<img width="236" alt="Screenshot 2022-06-13 at 16 15 45" src="https://user-images.githubusercontent.com/1777923/173362662-4c3987b4-8985-4f7e-9c33-d180b790105c.png">

**Comment by nklhtv** [comment]
Done
