### ISSUE TITLE
implement WatchedBitfield

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#34]
* [ ] just parses to `struct { anchor_video, bitmap }`
* [ ] find a data structure for the bitmap; implementing Iterator would be nice cause of `take_while` and similar
* [ ] `.mark_watched(videos: &[Video], video: &Video, watched: bool)`
    * identify if the anchor_video is within the same position of videos
         * it is -> continue
         * it is not -> re-create bitmap by rewriting the previous bitmap into a new bitmap of size `videos.len()` with an offset
         * set `bitmap[videos.index_of(video)] = watched`, but also resize bitmap in order to fit that index
         * set anchor_video to the last watched video
- [ ] document assumptions: stable order from the addon

**Comment by nklhtv** [comment]
current js implementation: https://github.com/Stremio/stremio-watched-bitfield

**Comment by core1024** [comment]
[WIP] current rust implementation https://github.com/Stremio/stremio-watched-bitfield-rs

**Comment by nklhtv** [comment]
implemented
