### ISSUE TITLE
Allow downgrading storage schema version

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-core#340]
Currently if you'd try to install an older version of the app, which used older version of storage, you'd fail to start the app due to error - `Downgrade storage schema version from 5 to 4 is not allowed`. Only way to solve it is to clear the app data fully and loose the settings.

**Comment by gmjimenezc** [comment]
Can I work on this?

**Comment by nklhtv** [comment]
thats how migrations work everywhere. for example you cannot downgrade an android app without losing the data.
not sure if we must support this case. whats the use case?

**Comment by TheBeastLT** [comment]
Use case would be if for example you've installed a new version of Stremio, but there's some breaking bug and you want to revert to an older version without the bug. Currently you wouldn't be able to do that, if that newer version had a migration, since after installing an older version the app would just crash on startup and the user would need to figure out that he needs to clear app data and loose the settings for it to work.
If there are no breaking changes during a migration, usually they are backwards compatible, ie if a new field was added then after installing an older version that new field can just be ignored, if a field was removed the it would be deserialized to default variable value?

**Comment by nklhtv** [comment]
we wont support this. i havent seen a database that can do this, but perhaps there is.
the 2 databases that we use, realm and indexeddb, throw error when you try to downgrade the schema version. the only option here is to clear the data completely
