### ISSUE TITLE
[Stremio Android TV] Unable to see my Trakt Watchlist Movies and Series

### ISSUE THREAD

**Issue by shscs911** [Stremio/stremio-core#363]
I'm unable to see my Trakt Watchlist for Movies and TV Series in Home and Discover sections.
I'm seeing this error, when selecting the Trakt Watchlist option:

`Env: Serialization error: data did not match any variant of untagged enum ResourceResponse`

https://ibb.co/JKj3gdp

Both Trakt History and Recommendations are showing up in Home and Discover, but watched movies are not getting added to Trakt
History automatically, like in previous Android app versions.

Tried logging out of Trakt from Linux, Android and Web and re-logging in. Still getting the same error.

Application: Stremio Android TV
Version: v1.5.3
APK: com.stremio.one-1.5.3-7048586-armeabi-v7a.apk
Device: FireTV Stick 4K

Found the same error in a GitHub issue closed 2 weeks ago:

https://github.com/Stremio/stremio-web/issues/194

**Comment by shscs911** [comment]
@jaruba I've uploaded my Movies Watchlist here:
https://pastebin.com/X4cCrqEN

**Comment by jaruba** [comment]
@shscs911 thanks, we'll look into it

**Comment by shscs911** [comment]
@jaruba Found the culprits.

https://trakt.tv/movies/the-lord-of-the-rings-the-two-towers-extended-2002
https://trakt.tv/shows/godzilla-2017

TMDB and TVDB URLs for these entries are invalid.

Is there any way you can restore the old behaviour, where it'll list out all the valid entries in Trakt Watchlist and just show an error for the invalid ones? If that's not possible, please consider showing an error message about the entries being invalid, so that users can remove them from their Watchlist.

Thanks a lot for helping me solve this. Love the work you guys have done so far on Stremio. Keep up the good work.

**Comment by jaruba** [comment]
@shscs911 

> Is there any way you can restore the old behaviour, where it'll list out all the valid entries in Trakt Watchlist and just show an error for the invalid ones?

We will do this, but we rewrote the core to be more strict. The Android TV app is the first app that uses the new core for now so it will show errors to alert us of non-standard behaviour. In this case, some items were sent in the Trakt Watchlist catalog that had `id: null`, the previous core would just ignore this (as you said), with the new core we have to fix the Trakt Watchlist official addon to not send metadata with such an ID. The result will be the same though, the broken items will be ignored.

**Comment by shscs911** [comment]
Awesome. That seems like a much better way to handle this issue.

Super cool to know about the separation of Trakt logic between stremio-core and Trakt addon.

Will the Trakt official addon be updated via `Sync Addons` once published or released in some future APK update to Stremio Android TV app?

**Comment by jaruba** [comment]
@shscs911 we fixed the issue with the trakt watchlist, if u restart the app it should work now, the fix was server side so it does not need an app update
