### ISSUE TITLE
Fix extra params encoding

### ISSUE THREAD

**Issue by nklhtv** [Stremio/stremio-core#372]
Use `utf8_percent_encode` for extra params [here](https://github.com/Stremio/stremio-core/blob/development/src/addon_transport/http_transport/http_transport.rs#L51) and [here](https://github.com/Stremio/stremio-core/blob/development/src/deep_links/query_params_encode.rs#L12)

**Comment by TRtomasz** [comment]
https://github.com/Stremio/stremio-core/issues/371

**Comment by nklhtv** [comment]
Done
