### ISSUE TITLE
Clear user object when session key does not exist

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-core#379]
**Description**
Right now if user kills his session android tv app does not lot out him so he use app without active session. This cause problems with synchronising user account between devices.

> yes, that should happen here: https://github.com/Stremio/stremio-core/blob/development/src/models/ctx/update_profile.rs#L315-L319
> in case we have CtxError::API with a specific error code we should clear the user object

**Comment by nklhtv** [comment]
Done
