### ISSUE TITLE
Add trakt activate/deactivate actions

### ISSUE THREAD

**Issue by TRtomasz** [Stremio/stremio-core#381]
New actions that should be added
ActivateTrakt: After user finished oauth2 flow, calling it should add trakt addon to his addons.
Deactivate trakt: Calling it should clear `profile.auth.user.trakt` and remove trakt addon from his addons

**Comment by TRtomasz** [comment]
The same could be added for FB import

**Comment by elpiel** [comment]
- [x] ActivateTrakt: After user finished oauth2 flow, calling it should add trakt addon to his addons. #369 
- [x] Deactivate trakt: Calling it should clear profile.auth.user.trakt and remove trakt addon from his addons 
@nklhtv I guess the button should uninstall the addon, but other than that, what should happen in core for Deactivating trakt? 
- [x] ~Facebook import - to be picked up next~ moved to #515

**Comment by TRtomasz** [comment]
@elpiel we should clear trakt token in user profile and push it to the api without trakttoken
