### ISSUE TITLE
Use last used subtitle when resuming after exiting Stremio

### ISSUE THREAD

**Issue by BP-onthemove** [Stremio/stremio-core#384]
When I watch half a movie and exit Stremio to resume an hour later after reopening Stremio I have to search the same subtitle I used again.

It would be great if Stremio resumed with the same subs instead of searching the sub again automically with the same risk of getting a non synced one again.

**Comment by TRtomasz** [comment]
Please use https://github.com/Stremio/stremio-features/issues repository to create feature requests.
