### ISSUE TITLE
Notifications and continue watching merging

### ISSUE THREAD

**Issue by elpiel** [Stremio/stremio-core#419]
### Notifications

Notifications should be implemented in core.

Here's what Alex said about this:

> https://github.com/Stremio/stremio-api-workers/blob/master/notifItem/updateFeeds.js
> i think here is the better place
> https://github.com/Stremio/stremio-api-workers/blob/7bf55fa0b2eed7fcf0d04ca8d27efe1f258c0603/notifItem/updateFeeds.js#L31-L37
> here specifically, it is doing a last videos request to cinemeta
> like this: https://v3-cinemeta.strem.io/catalog/series/last-videos/lastVideosIds=tt7440726,tt0944947.json
> with multiple imdb id
> (i think 50 IDs is the limit for last-videos)
> it gets those IDs from the library items of the user
> it then analyses the response to figure out if there are any new videos for those series

## Continue watching

After implementing the Notifications based on the JS impl we should be able to merge the Notifications with the Continue watching items and create a single Continue watching bar with new episodes of series showing in front when they come out.

Related tasks:
- [ ] #12

**Comment by Ivshti** [comment]
related #28

**Comment by elpiel** [comment]
Core PRs already implement the core functionality, only #12 remains to be solved so it's safe to close this issue .

- https://github.com/Stremio/stremio-core/pull/480
- https://github.com/Stremio/stremio-core/pull/486
- https://github.com/Stremio/stremio-core/pull/494 (Fixes #487 )
