### ISSUE TITLE
No Sound with Android TV Hdmi Arc

### ISSUE THREAD

**Issue by stickyfran** [Stremio/stremio-core#447]
This has been reported on a Redit before.
If you use an HDMI ARC output on Stremio it is going to crash the sound.

The workaround to this is toninstall VLC and use External Player in Stremio for Android TV

**Comment by stickyfran** [comment]
Fixed and i can't reproduce. Still some people seems to be having this issue on Reddit if anyone is able to reproduce it.

**Comment by TRtomasz** [comment]
For bugs reports please use https://github.com/Stremio/stremio-bugs/issues reposityory.
