### ISSUE TITLE
Subtitles unparsed codes (e.g. \an8) 

### ISSUE THREAD

**Issue by carlosvsilva** [Stremio/stremio-core#448]
Hi some subtitles provided by OpenSubtitles (in my case in Portugal Portuguese), have a format code in the beggining, that Stremio AndroidTV displays as text instead of ignoring/formatting accordingly, such as:
`{\an8}`
Can you please hide these codes from corrupting the dialogue of the actors?

Another amazing thing would be to default the subtitles to the actual **chosen** subtitles language in settings (between all sources, either internal to the video file or external from opensubtitles addon).
Right now I have **portuguese** selected in the settings as primary and brazilian as secondary, but in some movies, with both internal brazilian subtitle stream track and opensubtitles provided Portugal portuguese subtitles, Stremio selects the brazilian internal subtitle wrongly. I have **portuguese** as primary in Stremio settings.
Can you please bugfix?

Thanks

**Comment by TRtomasz** [comment]
i think his have been fixed some time ago. Ps for bugs please use https://github.com/Stremio/stremio-bugs/issues this repository
