### ISSUE TITLE
Add new filter in Explore section: Country of origin

### ISSUE THREAD

**Issue by carlosvsilva** [Stremio/stremio-core#449]
Hi can you please add a filter in Explore section that will allow me to browse only movies from Spain, or from France, or from Iran, or from Brazil, or from Portugal, and so on? One way it could be achieved is by filtering by original audio language (no dubs).

Thanks!

**Comment by Iheuzio** [comment]
That could be managed by addons

**Comment by carlosvsilva** [comment]
Or be allowed here: https://stremio.github.io/stremio-catalog-builder/

But unfortunately I can't find a way to achieve this anywhere :(

**Comment by TRtomasz** [comment]
This should be resolved on addon level. Addon should provide categories for specific countries.
