### ISSUE TITLE
Subtitles not syncronized on chromecast

### ISSUE THREAD

**Issue by weslst** [Stremio/stremio-core#451]
The subtitle works perfectly on my phone(Samsung S20). When I cast it to the google chromecast it gets really weird, sometimes it lags sometimes it's ahead, it doesn't work by adding or removing the delay because it's kinda random, if I change the delay it changes the delay randomly.

**Comment by TRtomasz** [comment]
For new bugs issues please use https://github.com/Stremio/stremio-bugs/issues repository
