### ISSUE TITLE
types: consider using Url

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#46]
consider using [Url](https://docs.rs/url_serde/0.2.0/url_serde/) for `transport_url`, addon `logo`/`poster`, meta `poster`/`logo`/`background`, stream `url`/`external_url`

The question here is whether we will benefit more than we're gonna risk from the added validation; the risk lies in that we might break certain add-on response working, even if only 1 of the fields is not a valid URL

**Comment by nklhtv** [comment]
all of those use url::Url now
