### ISSUE TITLE
Support for Media Keys to Control Playback

### ISSUE THREAD

**Issue by j0209** [Stremio/stremio-core#464]
Hello Stremio Team,

I've been enjoying the Stremio application and I believe that the addition of media keys support (play/pause, next track) for controlling playback would greatly enhance the user experience. This feature is commonly found in other media players and its inclusion in Stremio would provide a more seamless and intuitive control over playback.

The ability to control playback using media keys would enable users to easily play, pause, and switch videos without needing to navigate back to the Stremio window. This is particularly beneficial for users who are multitasking or using Stremio in the background. Moreover, this feature would significantly improve the user experience for those with Home Theater PCs (HTPCs), where a remote control or wireless keyboard with media keys is often used for control.

Here's a basic example of how this could be implemented in JavaScript:

```
document.addEventListener('keydown', function(event) {
    if (event.code === 'MediaPlayPause') {
        // Toggle play/pause
    } else if (event.code === 'MediaTrackNext') {
        // Go to next track
    }
});
```

This is a simplified example and the actual implementation might be more complex. For instance, media key events might not be reliably captured by the browser, especially when the application is not in focus. In such cases, additional Node.js packages like electron-media-service or electron-media-keys may be required to handle media keys at the system level.

I hope you'll consider this feature request. Thank you for your time and for the excellent work you've put into Stremio.

Best,
-J0209

**Comment by TRtomasz** [comment]
Please reopen issue using https://github.com/Stremio/stremio-features/ repository and please use new features template.
