### ISSUE TITLE
Add Network Interface Option

### ISSUE THREAD

**Issue by de-sawal** [Stremio/stremio-core#469]
An option that makes stremio connect through only the selected network interface. 

Users can choose whether stremio works with any interface or selected interface (eg. Ethernet, LAN* 1, Wi-Fi, or vpn interfaces like NordLynx). 

A similar implementation to that of "qBittorent -> Options -> Advanced -> Network Interface".
Would be massively helpful to users that only want to use the application through VPNs, and also applicable in other cases.

**Comment by TRtomasz** [comment]
For new features please use https://github.com/Stremio/stremio-features/issues repository.
