### ISSUE TITLE
behaviorHints type

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#47]
will be used in `MetaItem`, `MetaPreview`, `Stream`, `Manifest`

we can either use a `Vec<(name, value)>` or `HashMap`/`BTreeMap`; given how fast the latter is, there's no reason to not use it 

or we can make a separate type for Manifest, MetaItem and etc. and [capture additional fields](https://serde.rs/attr-flatten.html#capture-additional-fields)

**Comment by nklhrstv** [comment]
Done
