### ISSUE TITLE
[Feature-Request] Add in-memory caching option PC

### ISSUE THREAD

**Issue by Skorpinakos** [Stremio/stremio-core#476]
Since continuous writing in **permanent storage wears their finite write and read ops** it would be considerate to **allow in-memory caching** since many user's devices hold ample amounts of RAM (compared to the common 2.0 GB limit), which doesn't wear off.  

Is there any such option already that I missed ? Would it be hard to implement (since such functionality exists for the Android TV judging from other issues) ?

**Comment by TRtomasz** [comment]
Please reopen issue using https://github.com/Stremio/stremio-features/ repository and please use new features template.
