### ISSUE TITLE
Trakt is not scrobbling on Nvidia shield TV (2015) 

### ISSUE THREAD

**Issue by tundrablasen** [Stremio/stremio-core#483]
Headline says it all. 
I re-authenticated everything in my stremio user panel. logged out and logged in.
I deinstalled and re-installed the stremio app on my Nvidia Shield TV multiple times.
i cleared data and cache multiple times

**No Trakt Scrobbling is working. 
Not after i finished watching an episode/movie (Stremio does not marked the media in trakt as "Watched". 
Also the "Live Scrobbling" feature (that you see during playback on stremio, within the trakt website/App on the home screen what you are watching live right now including a progress bar) is not working**

Latest stremio app on all devices
**Trakt scrobble (even with Live scrobbeling) _**works fine**_ on my amazon fire tv 4K max in bedroom.**

But same setup on Nvidia shield tv (2015), no live scrobbeling, and no scrobbeling at the end of the episode/movie.

Before 1.5.11 it was working as expected. Fine with normal scrobbling and live scrobbling. (i recall i had no issues when using 1.5.8. but cannot guarantee the software version)

Application: Stremio Android TV
Version: v1.5.11 (latest available version)
APK: from official play store
Device: Nvidia Shield TV (2015) - latest SW update installed.

**Comment by tundrablasen** [comment]
Hey @TRtomasz 

can you give a super short feedback why you closed the issue?

**Comment by TRtomasz** [comment]
@tundrablasen  because you opened it twice in two different repos and that one is not the correct repo to open this kind of issues

**Comment by tundrablasen** [comment]
Thanks for letting me now. Good to know for the future
