### ISSUE TITLE
Feature Request: visible item titles

### ISSUE THREAD

**Issue by kabe-inc** [Stremio/stremio-core#507]
I've been an enthusiastic Stremio for some time and with the recent UI change I was hoping that users would be getting visible item titles everywhere and not just in the _Continue Watching_ list, or at least the option to toggle on/off.

The reason this is needed is because the thumbnails on some movies/series don't clearly display the title, meaning the user has to manually select them in order to verify what they are. 

![screenshot](https://i.postimg.cc/d3x3ngh4/titles-20230827104456.webp)

**Comment by TRtomasz** [comment]
For new feature/bugs reports please use stremio-bugs and stremio-features repository
