### ISSUE TITLE
Configurationf or visibility and sorting of Board view

### ISSUE THREAD

**Issue by Sarafian** [Stremio/stremio-core#509]
While I'm writing this, I've not received the recent UX updates, so I might be out of date.

Maybe it's my long addition to the Kodi UX but I prefer a less cluttered home/board view. I understand that stremio is replicating streaming and smart tv user experiences and for most that might be the best option but I would like to be able to control what shows in the first page, in what order and maybe some concept of favorites. Not sure if the library is the right option both for shows, movies and tv channels.

Somehow the order seems to be influenced by the order of addon installation. I remember when I had first installed `GreekTV` addon, the greek channels would show up very high and then after a recent reinstall they show up at the botton. I don't want to watch all greek channels but I would definetely like to be able to pin some somewhere. The continue watching section seems to do the trick at this moment.

So overall I would suggest the following UX improvement
* Visibility of sections provided by installed add-ons
* Order of visible sections
* Pinning-favorites unless that is the role of the library.

**Comment by TRtomasz** [comment]
For new feature/bugs reports please use stremio-bugs and stremio-features repository
