### ISSUE TITLE
Initial Buffering Issue on Android TV

### ISSUE THREAD

**Issue by xybydy** [Stremio/stremio-core#510]
Most of the torrent contents not buffering, all I see is splash screen with the movies logo on. But the weird thing is I can easily open the exact same source from stremio app on phone on the wifi network. 

I even did a factory reset on my android tv box (xiaomi mi box s) but the problem is still persists. Only rebooting the android tv fixes the issue, only for one or two playbacks.

I am not really sure if the app has logging feature to share for debugging.

**Comment by TRtomasz** [comment]
Please reopen issue using stremio-bugs repository and use the template  for new issues there.
