### ISSUE TITLE
No hdmi signal using framerate sync with Google tv

### ISSUE THREAD

**Issue by davedave85** [Stremio/stremio-core#511]
watching anything with framerate sync i got after i power off no signal on my google tv, the workaround to fix this is to unplug and plug the hdmi of google tv.
this only happens using stremio and shutdown the tv with stremio open, if i go back to google tv main menu everything is fine.

**Comment by TRtomasz** [comment]
For new feature/bugs reports please use stremio-bugs and stremio-features repository
