### ISSUE TITLE
Feature request: Always start video in external player (PC)

### ISSUE THREAD

**Issue by fedew04** [Stremio/stremio-core#519]
The Android app of Stremio has an option to always start the video in an external player. I suggest that this same feature is added to the Desktop app. The Desktop app already gives you the option to open in other players when you're inside the video, but it would be very useful if you could set it to open in an external player by default. 
![image](https://github.com/Stremio/stremio-core/assets/65686048/a5016d9e-0394-470c-bcfb-28bd254e249d)

**Comment by TRtomasz** [comment]
For new feature/bugs reports please use stremio-bugs and stremio-features repository
