### ISSUE TITLE
Library UI Customization (Change library tile size + change default sort)

### ISSUE THREAD

**Issue by ADHDefy** [Stremio/stremio-core#524]
It would be really cool to have some expanded features for the library UI, especially on Android. 

It would be great if we could resize the tiles and scale them down so that we could see more of our library at once. 

I would also like to see the option to set a default sorting method. Be default, it always sorts by "Recent," but it would be great of we could set it to default to "A-Z" or "Watched."

Being able to make custom lists, custom labels, or multiple libraries would be great, too, for library organization.

**Comment by TRtomasz** [comment]
for new features please use stremio-features repository
