### ISSUE TITLE
Download within Android app for watch later.

### ISSUE THREAD

**Issue by thanveeralisayed** [Stremio/stremio-core#526]
Wish if there was a feature to download the content within the app itself. So that we can watch when we are outside home network. Mobile data plans are limited. Also some debrid services are ip limited. I know we can direct the playback to any download manager and download.  But media center is important.

**Comment by Narcwis** [comment]
This is marked as completed but I can't find the option in the android App @TRtomasz

**Comment by gursuj** [comment]
Don't think this has been implemented in the Android version but you can install a download manager like [Navi](https://github.com/TachibanaGeneralLaboratories/download-navi), then use the External Player option when streaming, and select the download manager.
