### ISSUE TITLE
loopback messages

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#54]
There are certain messages that are meant to be, for most apps/cases, looped back into the system

This means reacting to an `Output` message by triggering a corresponding `Action`

Current list of those:

* `AddonsChanged` -> `PushAddons`, but only if there's an internet connection
* `LibUpdate(libitem)` -> `PushLibItem(libitem)`, but only if there's an internet connection; the `PushLibItem` will be ignored by the system if the user is not logged in
* `RecommendedLoad` -> `Load`; the `RecommendLoad` may happen as a response to `OpenMedia(url)` or `Open(libitem/metaitem/etc.)`
* `InstallAndOpenAddon`: this will install an add-on and then open it, so it will trigger a `RecommendedLoad` 
* certain kinds of User-related errors (that mean session expired) -> route to login screen

**Comment by Ivshti** [comment]
no need to document that, it's simply a standard part of writing models now

**Comment by nklhtv** [comment]
those things like libitem/addon push are implemented with internal actions.
the current runtime impl does not allow an effect to resolve with action, but only event or internal Msg
