### ISSUE TITLE
Improve playback UI on Android

### ISSUE THREAD

**Issue by ngocanhtve** [Stremio/stremio-core#542]
The new playback UI on Android almost fills whole the screen every time i select subtitles or playback speed. I don't know if this new playback UI follows any design philosophy or not, I just see that it causes a lot of inconvenience and makes the movie enjoyment experience worse.

Please make the panels smaller, make them partially transparent, and in general don't completely cover the content behind them.

**Comment by TRtomasz** [comment]
wrong repository for new features/bugs please use stremio-bugs stremio-features
