### ISSUE TITLE
If Stremio is started with no internet connection there is no way to refresh the app. Restart is required

### ISSUE THREAD

**Issue by K0-RR** [Stremio/stremio-core#558]
This is how Stremio looks when at the time of its startup internet is not available
![image](https://github.com/Stremio/stremio-core/assets/43277609/66366b76-43c3-440e-aaf9-00099a2ef7e8)

I believe the default chromium page should be replaced with something more in the style of the app itself.

**Comment by TRtomasz** [comment]
Press F5 button it will refresh the window  content.
