### ISSUE TITLE
[Desktop] Bottom bar settings (subtitles, playback speed etc) are not counting scrolling as movement so the bar is hiding itself

### ISSUE THREAD

**Issue by K0-RR** [Stremio/stremio-core#559]
If I want to enable subtitles and I need to scroll the languages list I also must move the cursor to prevent the list from disappearing.

If the issue is hard to understand I can record and link a video here.

**Comment by TRtomasz** [comment]
For bugs and features requests please use stremio-bugs and stremio-features repository.
