### ISSUE TITLE
Google TV Stremio App One Piece no information found about this error

### ISSUE THREAD

**Issue by osmansonsuz** [Stremio/stremio-core#569]
In my Google TV there is this problem where One Piece serie is not showing it properly.There is no problem in Desktop,Mobile,Web. As i see one piece episodes turned into japanese language in last two days. The problem started after this language changed.When i continue watching one piece in one click ok,sometimes the app crashes sometimes it shows this error.(No information found about this.)

To Reproduce Steps to reproduce the behavior:
Go to One Piece
Click on One Piece details
See error

Expected behavior A clear and concise description of what you expected to happen:
It should show just like the rest of the movies/series.

![image](https://github.com/Stremio/stremio-core/assets/77057974/3dd68f57-6fee-47f1-9bea-35e0075675fd)

![WhatsApp Image 2023-11-26 at 19 42 39](https://github.com/Stremio/stremio-core/assets/77057974/26850942-5d3d-4204-9249-eb3c216a745c)
This is after clicking the one piece details.
![WhatsApp Image 2023-11-26 at 19 42 39 (1)](https://github.com/Stremio/stremio-core/assets/77057974/243151c2-a45f-404b-a9ad-5c218926f03b)

TV Problem:
Device: TCL 65C635
OS: Google TV RP1A.200622.001 release-keys
Browser: Stremio App
Version: 1.6.4

**Comment by osmansonsuz** [comment]
I dont know how but it got fixed today.

**Comment by justauserid** [comment]
I still get this. I am on `1.9.12` version (fireTv). I was getting this in previous version as well.

I will add something from the catalgue (or search) and it will show up in "Continue Watching" or in "Library" and it will be fine. After few days I click on the thumbnail `No information found about this`. Same thumbail click works fine and then it doesn't. I remove it, search it again and then add again and then it works again until it doesn't. Rinse and repeat.

Stopping the app in Android (TV) settings works. But it has to be done everytime.
