### ISSUE TITLE
Streaming server error while loading shared libraries

### ISSUE THREAD

**Issue by 0Raik** [Stremio/stremio-core#608]
aur/stremio 4.4.164-1 (+39 1.45) (Out-of-date: 2024-01-01)

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 127

/opt/stremio/node: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
```

I recently updated Manjaro to the latest release as it is a rolling distro so I guess a library is missing now. I reinstalled Stremio (cloned, compiled) and not working. 

I apologize as I'm not savvy enough to fix this but any guide would be great. 

Thanks for your time reading this and thanks for helping creating such an amazing app. Have a wonderful day!

**Comment by TRtomasz** [comment]
you have to install missing libraries - libicui18n.so.73 https://github.com/Stremio/stremio-bugs/issues/635#issuecomment-1872915095

**Comment by 0Raik** [comment]
Thank you! Not sure why searching didn't show that post. 
I also asked around the Manjaro forums https://forum.manjaro.org/t/error-while-starting-application-missing-libraries/154444/12 and I was recommended against doing that. Instead had to replace nodejs `sudo pacman -Syu nodejs` which supposedly is the best solution. 

Thanks for the time. Have a great day!
