### ISSUE TITLE
Feature to allow picture in picture mode on mobile

### ISSUE THREAD

**Issue by Yotambu100** [Stremio/stremio-core#614]
Hey, First thing is I wanted to say thanks for creating Stremio. I use it daily and it's truly a pleasure.

One feature which will improve my experience using the application is picture in picture mode.
It would be really useful if the mobile app had the option to play the media in picture in picture mode just like Netflix/YouTube.

**Comment by speed-y** [comment]
Not sure why this feature was marked as completed without any comments or commits associated with it. Is this already implemented?
