### ISSUE TITLE
Feature Request: Pan-Scan, zoom and aspect ratio adjustments in player

### ISSUE THREAD

**Issue by OverWorldD** [Stremio/stremio-core#618]
Hi!

It would be really handy if the desktop player could do some basic pan-scan, zooming and aspect ratio adjustments directly. This of course can be done in VLC but it would be more handy to be able to do it directly in the player.

**Comment by TRtomasz** [comment]
Please use stremio-features for creating features requests. And dont forget to include details as we are not able to guess them,

**Comment by OverWorldD** [comment]
Okay! Thank you for the information!
