### ISSUE TITLE
Rehost in Gitea or Codeberg?

### ISSUE THREAD

**Issue by fenglengshun** [Stremio/stremio-core#623]
After the recent [Tachiyomi takedown](https://tachiyomi.org/news/2024-01-13-goodbye), I've been wary of projects like Stremio being hosted on github, or even gitlab, due to being in the US and the risks possessed by takedowns.

Is there any interest in moving Stremio to be hosted on Codeberg which seems to be safer, or maybe even self-hosted somewhere with Gitea? Ideally, in my opinion it should be hosted with Gitea in Russia so that it'd be much more immune to potential takedowns.

**Comment by TRtomasz** [comment]
There are no such plans 😄
