### ISSUE TITLE
Bug: Episodes not showing on TV or phone app

### ISSUE THREAD

**Issue by jmontezuma26** [Stremio/stremio-core#629]
I set up stremio + torrentio + RD yesterday on my computer and it works perfectly! However, there are missing episodes from season 2 of Love on the Spectrum (see screenshots) on my android phone (pixel 8 pro) and nvidia shield tv (android TV). I also posted on reddit [here](https://www.reddit.com/r/Stremio/comments/19en5fj/episodes_not_showing_on_tv_or_phone_app_repost/?share_id=uPeUu9W895IpZawVRApxP&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1) and it looks like the issue is reproducible according to another user

A workaround i found is that if i start a missing episode on my computer, i can resume on my phone. the missing episodes just dont show up when searching, under the season.

Things ive tried:

Clear data+cache on tv, phone, and computer

reinstall on tv, phone, and computer (deleting temp files as well

fully close app/force stop on tv phone and computer

creating a new account and reinstalling from scratch

Many Thanks! Stremio looks like an absolute gamechanger and it would be awesome to get it working on my other devices

![image](https://github.com/Stremio/stremio-core/assets/76074296/a97352d4-2d79-4a3a-820d-09044b814c16)

![image](https://github.com/Stremio/stremio-core/assets/76074296/ab51383c-53f5-4948-9b9a-3afd45eb4d90)

**Comment by TRtomasz** [comment]
First of all please use stremio-bugs and stremio-features to report issues/feature requests. If this is still happening please let us know.
