### ISSUE TITLE
Suggestion: Detect and disable broken addons

### ISSUE THREAD

**Issue by master3395** [Stremio/stremio-core#631]
Perhaps a good idea to auto detect and disable addons, that can't detect the files/links?
That way, the user will have less errors showing up, and if disabled, perhaps add a small text around the addon in the addon page, example: "Disabled because of issues".
![420071877_7822827654401212_3371072101385108755_n](https://github.com/Stremio/stremio-core/assets/4199669/86da9566-6f41-4cb6-aaa2-1b09800e72c4)

**Comment by TRtomasz** [comment]
What if it starts working after one minute? Also this is not a repository te report such requests please use stremio-bugs and stremio-features repositories
