### ISSUE TITLE
cursor theme isnt being respected under plasma 6 wayland

### ISSUE THREAD

**Issue by pollux78** [Stremio/stremio-core#648]
im using stremio flatpak with xdg-desktop-portal kde and gtk installed under plasma 6 wayland 
this is the only app for me that doesnt respect the theming of the cursor on plasma 6, on plasma 5 it had no issues with the cursor
![Screenshot_20240308_203844](https://github.com/Stremio/stremio-core/assets/81181814/25a0d12e-f58a-44c8-9eac-6feb4af9a690)

**Comment by pollux78** [comment]
the cursor should look like this when hovering over stremio
![Screenshot_20240308_204154](https://github.com/Stremio/stremio-core/assets/81181814/6097130a-839d-47f4-ba09-39a3a3ba195d)

**Comment by TRtomasz** [comment]
Please open bugs reports in stremio-bugs, but this moste likely will not be fixed as it is a super low priority issue.
