### ISSUE TITLE
Loadable::NotLoaded and Unload

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#66]
implement an Unload action and a NotLoaded state

or in general, some way to unload models

**Comment by nklhrstv** [comment]
Unload action is implemented. Instead of Loadable::NotLoaded an Option<Loadable> is used.
Do you think that replacing Loadable with Poll<Result<T>> is ok?

**Comment by Ivshti** [comment]
an Option is fine, Poll is fine too

**Comment by nklhtv** [comment]
Will keep the current api of Loadable and use Option<Loadable<_, _>> where we need to mark a resource as not loaded
