### ISSUE TITLE
Feature Request: Multiple profiles and switching between them

### ISSUE THREAD

**Issue by scalpmonkey** [Stremio/stremio-core#660]
Issue: Individual settings and especially watched content is very important when device is used from multiple persons. At this moment only one account/profile can be logged on Stremio which make only one Trakt account to be connected to it. This way whatever is watched is mixed up and screw the meta for every person. Addons settings is another issue that goes with this.

Solution: Option to choose profile when starting Stremio or simply switch between profiles.

**Comment by scalpmonkey** [comment]
Is this implemented? Are we missing something?

**Comment by TRtomasz** [comment]
https://github.com/search?q=repo%3AStremio%2Fstremio-features%20profile&type=code

**Comment by scalpmonkey** [comment]
> https://github.com/search?q=repo%3AStremio%2Fstremio-features%20profile&type=code

No matches. Dead end.

**Comment by TRtomasz** [comment]
look on the left side menu there is item called "issues"
