### ISSUE TITLE
the meta interface of the plugin I wrote does not show anything (works in the web version)

### ISSUE THREAD

**Issue by aflextr** [Stremio/stremio-core#668]
the plugin I wrote used to work smoothly, but since 1 week it gives a black screen in the stremio application.(there is a problem in android and windows versions)

https://github.com/Stremio/stremio-core/assets/53778891/4faeb722-7c70-44bc-8304-2a9a76b0ad0b

**Comment by TRtomasz** [comment]
First of all, this is wrong repository, for bugs reports please use stremio-bugs. Second of all, it does not containt any details, are we supposed to guess what is wrong based on the video? Please open ne issue in stremio-bugs with all required details, will help a lot if you can share addon/addon code.
