### ISSUE TITLE
Allow more than 8 items in the Continue Watching section

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-core#672]
There wasn't any restriction on the number of items in the Continue Watching section in the older versions of stremio.
It would be great if the 8 item restriction could be removed from the current version.

**Comment by elpiel** [comment]
@rp1231 thank you on reporting this issue.
Could you specify what app are you using, where is this restriction, etc. in order to see if it's a core issue or one of the apps?

**Comment by rp1231** [comment]
@elpiel I'm referring to the desktop apps.
This issue exists on the desktop version of the apps on windows and on linux.
Here is the screenshot:
![Screenshot from 2024-05-07 16-06-50](https://github.com/Stremio/stremio-core/assets/47380919/3472e706-6dc2-44d3-9814-ae349b4ac6ba)
As you can see the continue watching section doesn't extend beyond 8 items.

**Comment by elpiel** [comment]
The desktop app does not use `stremio-core`.
I will share this issue with the Desktop develop @core1024 to take a look if this is intended on an actual bug.

**Comment by elpiel** [comment]
We discussed this internally and on desktop, at least currently, we do not plan to fix this issue.

Thank you once again for raising this issue.
Do note that this is a non-app related repository with an app related issue.
You can use proper channels to raise such issues like https://github.com/Stremio/stremio-bugs/issues/
