### ISSUE TITLE
UX: sync lib item when opening detail page

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#69]
when opening the detail page, pull the latest libitem and update it in the model if it's newer

this solves the following UX issue: opening a detail page, and playing an episode, and it turns out you already watched it cause the state wasn't synced with your other device

**Comment by Bananaman** [comment]
+1 this is still an issue.

**Comment by Bananaman** [comment]
I wonder if this cna be worked around by force-quitting Stremio or restarting the target device, and starting it again. Does that force a sync of all media item states?

**Comment by nklhtv** [comment]
@Bananaman 
as a temporary workaround this should do the job

**Comment by nklhtv** [comment]
This must be implemented by returning Internal::LibrarySyncPlanResult message from ActionLoad handler in [MetaDetails model](https://github.com/Stremio/stremio-core/blob/development/src/models/meta_details.rs#L38-L80)
