### ISSUE TITLE
BUG: Using search deeplinks on Android Fails

### ISSUE THREAD

**Issue by Wamy-Dev** [Stremio/stremio-core#695]
Hey there, when using the Stremio deep link:

`stremio://search?search=query`

and query is an URLEncoded link pointing to a direct file, and the Stremio deep link is opened from a browser, it shows 

AddonDetail

Error occurred while adding addon.

The link is a direct link to a file, not an addon, furthermore, the search directive should be pointing it in the correct direction internally. This is not an issue on Linux or Mac, just on Android, the latest version.

**Comment by TRtomasz** [comment]
Android app does not allow playing links directly from the search this is not a bug, btw for issues/features please use stremio-bugs stremio-features repos.
