### ISSUE TITLE
Bug: Stremio not downloading the remaining content of the content I am watching

### ISSUE THREAD

**Issue by paramveer665** [Stremio/stremio-core#713]
If I start watching something Stremio stops its download and downloading speed falls to somewhere 60 kb while my internet has speed upto 10MBps. I am aware of Stremio puts a limit on bandwidth. But once I pause the stream speed increases again 2 MBps to 3MBps only when I am watching the stream it falls

##PAUSED
![Screenshot_2](https://github.com/user-attachments/assets/b0286cdb-2778-41d5-806f-a6ed48e20ca2)

**Comment by TRtomasz** [comment]
If you dont enable cache it uses only 50MB in memory buffer. also for bugs reports please use stremio-bugs repo.
