### ISSUE TITLE
Feature Request: Brightness/ Volume slider in internal player for android smartphones

### ISSUE THREAD

**Issue by thanveeralisayed** [Stremio/stremio-core#722]
I know it's a lot to ask, especially since you provide your app for free. Unlike any other streaming application, you cover all of my devices—Windows PC, Linux laptop, Samsung TV, and my Android phone. I don't think even the big companies with their monthly fees offer this much coverage. Everything I watch is synced across all my devices, thanks to this wonderful app.

Regarding brightness and volume controls, I know I can use an external player with Stremio to access this feature. However, if this slider feature were available within the app, most of us would prefer watching content directly inside the Stremio app. External players don't always sync as well as the internal player; sometimes the resume function doesn’t work properly.

**Comment by TRtomasz** [comment]
this is stremio-core repo.
