### ISSUE TITLE
Metadata subtitles problem

### ISSUE THREAD

**Issue by sen-6ei** [Stremio/stremio-core#726]
As other users already pointed out, there's a mismatch in some series (expecially anime) because of metadata. 

My problem is: i'm italian and i need italian subs for animes. 
During my research it's my understanding that Cinemeta official addon is using TVDB as database for Movies and TV shows, but you have as an official subtitles Addon OpenSubtitles which is using IMDB.
So as a concrete example "Hunter x Hunter (2011)" on IMDB is 148 episodes all in one season, instead of 3 season as TVDB. So using any catalog addon even the ones that have different split (Kitsu for example stores all 148 episodes in one season) I can choose subtitles up to the 58th episode, i.e. the last one of Season I according to Cinemeta. From season 2 episode 1 and season 1 episode 59 (Kitsu) there aren't any subs in any language, not only italian. 

I want to add that using a "trick" that i learned on Reddit i managed to uninstall Cinemeta, but the problem persist. So the TVDB usage is embedded in some logic that i'm not aware of.

**Comment by TRtomasz** [comment]
we cant controll what metadata is opensubtitle using and most certainly i dont think it is possible for us to somehow overwrite it in the addon for it to find correct episode number, btw this is stremio-core repository.

**Comment by sen-6ei** [comment]
You've implemented opensubtitles as out-of-the-box subtitles provider. Why your internal management of content metadata uses a different Database? Why there isn't the possibility to over write default database removing cinemeta? Why there isn't a middleware doing the conversion from TvDB to IMDb IDs given the fact that you as Publisher of the App decided to set Opensubtitles as Default?
