### ISSUE TITLE
stremio playback error on macOS app

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-core#728]
Hello,

im using the stremio app on MacOS and everytime i try to play a video/movie it comes up with the "Playback error, please try again." i tried closing and reopening the app, failed. i tried using a vpn on wireguard and openVPN, failed. i tried stremio on a virtual machine with a vpn, failed. any help?

this is my streamio and macos versions. thank you
<img width="98" alt="Screenshot 2024-10-19 at 16 24 12" src="https://github.com/user-attachments/assets/a4981e43-eb2d-42da-b36f-8933367a398c">

<img width="139" alt="Screenshot 2024-10-19 at 16 24 37" src="https://github.com/user-attachments/assets/4419ed3e-ae8e-4b61-a113-52031ac21d82">

**Comment by TRtomasz** [comment]
please reopen issue in stremio-bugs with all relevant details
