### ISSUE TITLE
LibRecent model: items with notifications

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#75]
Because of the separate notifications UI, this is not so important, and one might argue it actually makes the UI less obvious/straight forward. **So it's very low priority**

first sort by the date of the first notification, second sort by lastWatched; the goal here is to show items with notifications (but only if overallTimeWatched > 0)

warning: this means continue watching might need to show items that are not `.is_in_continue_watching`, so we have to rename that method or change it's functionality; consider renaming that to `is_recent` or something

This means we may have to move notifications to the context, since it affects the order and contents of Continue watchinb

**Comment by elpiel** [comment]
This was implemented #480 and #450
