### ISSUE TITLE
Caching on http streaming

### ISSUE THREAD

**Issue by Lihael** [Stremio/stremio-core#758]
Does stremio not cache when http streaming? There is an option in the settings for cache size. Does this not work when watching http streams? I have a spotty connection to the streaming services, so it would be very helpful for stremio to attempt to download the whole video instead of just the next 30 seconds when watching, which would help smooth out the experience and make seeking easier

**Comment by TRtomasz** [comment]
Caching does not work for http streaming

**Comment by Lihael** [comment]
> Caching does not work for http streaming

Is there a reason why we can't have caching for http streaming? Or is it just unimplemented? Seeking often takes very long for me on stremio because of this.
