### ISSUE TITLE
Split addons/mod.rs in multiple files

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-core#99]
There’s a few important things there, eg ResourceResponse and Descriptor that should be split out

**Comment by YanivBir** [comment]
Hi, is it still open?
Can I work on it? @nklhrstv @Ivshti

**Comment by nklhrstv** [comment]
@YanivBir 
Hi. This issue is done. I forgot to close it

**Comment by YanivBir** [comment]
Hi Nikola,

Thanks for your answer.

I use Stremio every day, and I want to contribute so much to it.

Do you know of some issue that I can work on it?

(I instead in Stremio core project)

Thanks,
